"""Markdown report of a fisher_bestfit*.json re-score, checked against the native-distance one.

    python report_fisher_bestfit.py fisher_bestfit_snr200.json  -> RESULTS_snr200.md

At a renormalised SNR the best fit and overlap must be unchanged and every sigma must scale by
SNR_native / SNR; the 'check' table shows how far each set is from that.  CPU, seconds.
"""

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
NATIVE = os.path.join(HERE, "fisher_bestfit.json")
PARAMS = ("m1", "m2", "p0", "e0", "Phi_phi0", "Phi_r0")
MODELS = (("vacuum", "0PA"), ("pn", "0PA+PN"))


def param(m, name, key):
    return m[key][m["names"].index(name)]


def md_setup(sets):
    rows = ["## Sets and SNR normalisation", "",
            "| set | e0 | dist native [Gpc] | SNR native | dist [Gpc] | SNR | "
            "A share | E share | T share |", "|---|---|---|---|---|---|---|---|---|"]
    for s in sets:
        ch = s["channel_snr"]
        tot = sum(v ** 2 for v in ch.values())
        share = [f"{100 * ch[c] ** 2 / tot:.4f}%" for c in "AET"]
        rows.append(f"| {s['tag']} | {s['injection']['e0']:g} | {s['dist_native']:g} | "
                    f"{s['snr_native']:.3f} | {s['dist']:.6f} | {s['snr']:.3f} | "
                    + " | ".join(share) + " |")
    return rows + ["", "Share = fraction of SNR^2 carried by each channel.", ""]


def md_check(sets, native):
    rows = ["## Check against the native-distance re-score", "",
            "Expected: overlap unchanged, sigma x SNR_native / SNR.", "",
            "| set | model | overlap | overlap native | max rel. sigma deviation from scaling |",
            "|---|---|---|---|---|"]
    for s in sets:
        n = native[s["tag"]]
        for t, label in MODELS:
            m, mn = s["models"][t], n["models"][t]
            expect = np.array(mn["sigma"]) * n["snr"] / s["snr"]
            dev = np.max(np.abs(np.array(m["sigma"]) / expect - 1))
            rows.append(f"| {s['tag']} | {label} | {m['overlap']:.12f} | {mn['overlap']:.12f} | "
                        f"{dev:.2e} |")
    return rows + [""]


def md_overlap(sets):
    rows = ["## Overlap", "",
            "| set | 0PA overlap | 0PA mismatch | 0PA chi2 | PN overlap | PN mismatch | PN chi2 | "
            "mismatch 0PA / PN |", "|---|---|---|---|---|---|---|---|"]
    for s in sets:
        v, p = s["models"]["vacuum"], s["models"]["pn"]
        rows.append(f"| {s['tag']} | {v['overlap']:.12f} | {v['mismatch']:.3e} | {v['chi2']:.4e} | "
                    f"{p['overlap']:.12f} | {p['mismatch']:.3e} | {p['chi2']:.4e} | "
                    f"{v['mismatch'] / p['mismatch']:.2f}x |")
    return rows + [""]


def md_bias(sets):
    rows = ["## Bias, sigma, bias / sigma", "",
            "Each cell: bias (sigma) [bias/sigma].  bias = best fit - injection.", "",
            "| set | model | " + " | ".join(PARAMS) + " | C_p | C_e |",
            "|---|---|" + "---|" * (len(PARAMS) + 2)]
    for s in sets:
        for t, label in MODELS:
            m = s["models"][t]
            cells = [f"{param(m, n, 'bias'):+.3e} ({param(m, n, 'sigma'):.3e}) "
                     f"[{param(m, n, 'bias_over_sigma'):+.3f}]" for n in PARAMS]
            devs = [f"{param(m, n, 'theta'):+.3g} +- {param(m, n, 'sigma'):.3g}"
                    if n in m["names"] else "-" for n in ("dev_1", "dev_2")]
            rows.append(f"| {s['tag']} | {label} | " + " | ".join(cells + devs) + " |")
    return rows + [""]


def main(path):
    sets = json.load(open(path))
    native = {s["tag"]: s for s in json.load(open(NATIVE))}
    suffix = os.path.basename(path).replace("fisher_bestfit", "").replace(".json", "")
    lines = [f"# Fisher / overlap re-score at the best fits{' (' + suffix.strip('_') + ')' if suffix else ''}",
             "", f"Generated by `report_fisher_bestfit.py` from `{os.path.basename(path)}` "
             "-- do not hand-edit.", ""]
    for section in (md_setup, md_overlap, md_bias):
        lines += section(sets)
    if os.path.abspath(path) != NATIVE:
        lines += md_check(sets, native)
    out = os.path.join(HERE, f"RESULTS{suffix or '_native'}.md")
    open(out, "w").write("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main(sys.argv[1])
