"""Per-channel (A, E, T) SNR of the environmental signal of sets 4 and 5 at several dt.

A signal carrying power above Nyquist (0.5/dt) aliases, and the tell is spurious power in the
otherwise near-null T channel.  So compare the A/E/T split across dt: if it is stable, the
signal is resolved; if it shifts with dt, the coarser sampling is aliasing it.

Band: the pipeline's [fmin, fmax] = [1e-5, 0.1] Hz, which at dt = 10 is clipped by Nyquist
(0.05 Hz).  At dt = 2.5 the SNR is also given up to its Nyquist (0.2 Hz), to show whether
anything lives above 0.1 Hz.  Native distance, T = 0.99 x plunge, as in every run.

Run:  python snr_channels_dt.py      -> snr_channels_dt.json, snr_channels_dt.md   (GPU)
"""

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)
from env_cv import Config, build_scoring, observation_time, log                  # noqa: E402
from fisher_bestfit import CONFIGS, channel_snr                                  # noqa: E402

SETS = ("set 4", "set 5")
# (dt [s], fmax [Hz]); fmax = None -> up to Nyquist
CASES = ((2.5, 0.1), (2.5, None), (5.0, 0.1), (10.0, 0.1))
OUT = os.path.join(HERE, "snr_channels_dt")


def measure(tag, dt, fmax):
    cfg = Config(os.path.join(ROOT, CONFIGS[tag][1]))
    cfg.dt = dt
    cfg.fmax = fmax if fmax is not None else 0.5 / dt
    T = observation_time(cfg)
    scoring = build_scoring(cfg, T)
    log(f"[SNR ] {tag} dt = {dt:g} s, band [{cfg.fmin:g}, {cfg.fmax:g}] Hz: "
        f"SNR = {scoring['snr']:.6f}")
    ch = channel_snr(scoring)
    tot = sum(v ** 2 for v in ch.values())
    return dict(set=tag, dt=dt, nyquist=0.5 / dt, fmax=cfg.fmax, T=T, snr=scoring["snr"],
                channel_snr=ch, channel_share={c: v ** 2 / tot for c, v in ch.items()},
                n_samples=int(scoring["signal"].shape[-1]))


def write_md(rows):
    lines = ["# Per-channel SNR vs dt, sets 4 and 5", "",
             "Generated by `snr_channels_dt.py` -- do not hand-edit.  Share = fraction of "
             "SNR^2 in each channel.  Native distance (16.344 Gpc).", "",
             "| set | dt [s] | Nyquist [Hz] | band max [Hz] | SNR | A SNR | E SNR | T SNR | "
             "A share | E share | T share |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        c, s = r["channel_snr"], r["channel_share"]
        lines.append(f"| {r['set']} | {r['dt']:g} | {r['nyquist']:g} | {r['fmax']:g} | "
                     f"{r['snr']:.4f} | {c['A']:.4f} | {c['E']:.4f} | {c['T']:.4f} | "
                     f"{100 * s['A']:.4f}% | {100 * s['E']:.4f}% | {100 * s['T']:.4f}% |")
    open(OUT + ".md", "w").write("\n".join(lines) + "\n")


def main():
    rows = []
    for tag in SETS:
        for dt, fmax in CASES:
            rows.append(measure(tag, dt, fmax))
            json.dump(rows, open(OUT + ".json", "w"), indent=1)
    write_md(rows)
    log(f"[saved] {OUT}.json, {OUT}.md")


if __name__ == "__main__":
    main()
