"""Critical SNR on the (a, e0) grid, 0PA vs 0PA + PN, as in Fisher_results/plot_bias.py:
    1D : rho_crit = SNR0 z_CL / |worst bias/sigma|,  z_CL = Phi^-1(1/2 + CL/2), worst over the physical
         parameters (for 0PA + PN: own sigma, C_p and C_e marginalised but never the worst parameter)
    nD : rho_crit = SNR0 D_CL / D,  D_CL^2 = chi^2_k quantile at CL, D over the k physical parameters
         (C_p, C_e marginalised for 0PA + PN)
SNR0 = 20; both bias measures scale linearly with SNR, so rho_crit does not depend on SNR0. Below
rho_crit the bias is hidden at that CL.
Each is made with the phases and with Phi_phi0, Phi_r0 left out (1D: not eligible as worst
parameter; nD: marginalised).
    -> plots/critical_snr/{with,no}_phases/snr_crit_{CL}CL.png, snr_crit.md

Run:  python plot_critical_snr.py
"""
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm, TwoSlopeNorm
from scipy import stats

from bias_data import ND_SETS, load_bias
from common import (DIV, FLAG_NOTE, LABEL, SEQ, C, SURFACE, TEXT_2, grid, ink_on, mark_flags,
                    out_file, style_axes)

SNR0 = 20.0
CLS = (0.90, 0.99)
RATIO_LIM = 2.0         # colour range of the ratio panels: 10^-2 .. 10^2
VARIANTS = {"": ("with_phases", "with phases"), "_np": ("no_phases", "phases left out")}


def worst(z, variant):
    """Largest |bias/sigma| over the physical parameters; C_p, C_e are never eligible."""
    finite = {n: v for n, v in z.items() if n in C.PHYS and np.isfinite(v)
              and not (variant == "_np" and n in C.PHASES)}
    name = max(finite, key=lambda n: abs(finite[n]))
    return name, finite[name]


def critical(p, cl, variant):
    """rho_crit 1D and nD for both templates at confidence level cl."""
    z_cl = stats.norm.ppf(0.5 + cl / 2)
    out = {}
    for tag, z_key, D_key in (("0pa", "z_0pa", "0pa"), ("pn", "z_pn", "pn_phys")):
        D_cl = np.sqrt(stats.chi2.ppf(cl, len(ND_SETS[variant][D_key])))
        D = p[f"D_{D_key}{variant}"]
        name, z = worst(p[z_key], variant)
        out[f"1D_{tag}"], out[f"worst_{tag}"] = SNR0 * z_cl / abs(z), name
        out[f"nD_{tag}"] = SNR0 * D_cl / D
    return out


def heat(ax, fig, values, labels, cmap, norm, title, cbar_label, pts):
    im = ax.imshow(values.astype(float), origin="lower", cmap=cmap, norm=norm, aspect="auto")
    for (y, x), text in np.ndenumerate(labels):
        ax.text(x, y, text, ha="center", va="center", fontsize=8,
                color=ink_on(cmap(norm(values[y, x]))))
    style_axes(ax, title)
    ax.set_facecolor(SURFACE)
    mark_flags(ax, pts)
    cb = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03)
    cb.set_label(cbar_label, color=TEXT_2)
    cb.outline.set_visible(False)


def rho_label(c, kind, tag):
    v = c[f"{kind}_{tag}"]
    if kind == "1D":
        return f"{v:.3g}\n{LABEL[c[f'worst_{tag}']]}"
    return f"{v:.3g}"


def figure(pts, crits, cl, variant):
    vals = [c[f"{k}_{t}"] for c in crits.values() for k in ("1D", "nD") for t in ("0pa", "pn")]
    norm = LogNorm(min(vals), max(vals))
    fig, axes = plt.subplots(2, 3, figsize=(20, 11.5), facecolor=SURFACE)
    for row, kind in enumerate(("1D", "nD")):
        for col, (tag, name) in enumerate((("0pa", "0PA"), ("pn", "0PA + PN"))):
            npar = len(ND_SETS[variant]["0pa" if tag == "0pa" else "pn_phys"])
            what = "worst parameter, own σ" if kind == "1D" else f"{npar} physical" + (
                ", C marginalised" if tag == "pn" else "")
            heat(axes[row, col], fig, grid(pts, lambda p, k=f"{kind}_{tag}": crits[p["idx"]][k]),
                 grid(pts, lambda p: rho_label(crits[p["idx"]], kind, tag)), SEQ, norm,
                 f"{kind} critical SNR, {name} ({what})", "ρ_crit", pts)
        ratio = grid(pts, lambda p: np.log10(crits[p["idx"]][f"{kind}_pn"] / crits[p["idx"]][f"{kind}_0pa"]))
        heat(axes[row, 2], fig, np.clip(ratio.astype(float), -RATIO_LIM, RATIO_LIM),
             grid(pts, lambda p: f"{crits[p['idx']][f'{kind}_pn'] / crits[p['idx']][f'{kind}_0pa']:.3g}"),
             DIV.reversed(), TwoSlopeNorm(0.0, -RATIO_LIM, RATIO_LIM),
             f"{kind}: ρ_crit(0PA + PN) / ρ_crit(0PA)", "log10 ratio (blue: PN hides the bias longer)",
             pts)
    fig.suptitle(f"EMRI, 1PA signal: critical SNR at {cl * 100:.0f}% CL, {VARIANTS[variant][1]} "
                 "(bias undetectable below ρ_crit)", x=0.01, ha="left", fontsize=13)
    fig.text(0.01, 0.01, FLAG_NOTE, fontsize=8.5, color=TEXT_2)
    fig.tight_layout(rect=(0, 0.03, 1, 0.96))
    return fig


def markdown(pts, crits_by_cl, variant):
    lines = [f"# EMRI critical SNR, 0PA vs 0PA + PN, {VARIANTS[variant][1]}", "",
             "Generated by plot_codes/plot_critical_snr.py. 1D: worst parameter (own sigma); "
             f"nD: the {len(ND_SETS[variant]['0pa'])} physical parameters "
             f"({', '.join(ND_SETS[variant]['0pa'])}), C_p and C_e marginalised for 0PA + PN.", ""]
    for cl, crits in crits_by_cl.items():
        lines += [f"## {cl * 100:.0f}% CL", "",
                  "| idx | a | e0 | gain | 1D 0PA | 1D PN | nD 0PA | nD PN |", "|" + "---|" * 8]
        for p in pts:
            c = crits[p["idx"]]
            nd = [f"{c[f'nD_{t}']:.3g}" for t in ("0pa", "pn")]
            lines.append(f"| {p['idx']} | {p['a']:+.1f} | {p['e0']:.1f} | {p['gain']:.2f} "
                         f"| {c['1D_0pa']:.3g} ({c['worst_0pa']}) | {c['1D_pn']:.3g} ({c['worst_pn']}) "
                         f"| {nd[0]} | {nd[1]} |")
        lines.append("")
    return "\n".join(lines)


def main():
    pts = load_bias(SNR0)
    for variant, (folder, _) in VARIANTS.items():
        crits_by_cl = {}
        for cl in CLS:
            crits = {p["idx"]: critical(p, cl, variant) for p in pts}
            crits_by_cl[cl] = crits
            out = out_file("critical_snr", folder, f"snr_crit_{cl * 100:.0f}CL.png")
            figure(pts, crits, cl, variant).savefig(out, dpi=160, facecolor=SURFACE)
            plt.close("all")
            print(f"-> {out}")
        out = out_file("critical_snr", folder, "snr_crit.md")
        out.write_text(markdown(pts, crits_by_cl, variant))
        print(f"-> {out}")


if __name__ == "__main__":
    main()
